//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeVista.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class APİEntegrasyon
    {
        public int APİİstekİD { get; set; }
        public string APİAdi { get; set; }
        public string İstekTuru { get; set; }
        public string İstekParametreleri { get; set; }
        public byte[] İstekZamani { get; set; }
    }
}
