//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeVista.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Basarilar
    {
        public int BasariİD { get; set; }
        public int KullaniciİD { get; set; }
        public int SertifikaİD { get; set; }
        public System.DateTime BasariTarihi { get; set; }
        public string Açıklama { get; set; }
    
        public virtual Kullanicilar Kullanicilar { get; set; }
        public virtual Sertifikalar Sertifikalar { get; set; }
    }
}
