//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeVista.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bloglar
    {
        public int BlogİD { get; set; }
        public int KullaniciİD { get; set; }
        public string Baslik { get; set; }
        public string İcerik { get; set; }
        public System.DateTime YayinlanmaTarihi { get; set; }
        public string Etiketler { get; set; }
        public Nullable<int> ResimID { get; set; }
    
        public virtual Kullanicilar Kullanicilar { get; set; }
        public virtual Resimler Resimler { get; set; }
    }
}
