//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeVista.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CodeVistaEntities : DbContext
    {
        public CodeVistaEntities()
            : base("name=CodeVistaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<APİEntegrasyon> APİEntegrasyon { get; set; }
        public virtual DbSet<Basarilar> Basarilar { get; set; }
        public virtual DbSet<Bloglar> Bloglar { get; set; }
        public virtual DbSet<CalismaGruplari> CalismaGruplari { get; set; }
        public virtual DbSet<DilKonulari> DilKonulari { get; set; }
        public virtual DbSet<Diller> Diller { get; set; }
        public virtual DbSet<EgitimKaynaklari> EgitimKaynaklari { get; set; }
        public virtual DbSet<İndirimKuponlari> İndirimKuponlari { get; set; }
        public virtual DbSet<Kategoriler> Kategoriler { get; set; }
        public virtual DbSet<Kaynaklar> Kaynaklar { get; set; }
        public virtual DbSet<Konular> Konular { get; set; }
        public virtual DbSet<KullaniciEtkilesimleri> KullaniciEtkilesimleri { get; set; }
        public virtual DbSet<KullaniciFavorileri> KullaniciFavorileri { get; set; }
        public virtual DbSet<KullaniciGeriBildirimleri> KullaniciGeriBildirimleri { get; set; }
        public virtual DbSet<Kullaniciİstatistikleri> Kullaniciİstatistikleri { get; set; }
        public virtual DbSet<Kullanicilar> Kullanicilar { get; set; }
        public virtual DbSet<KullaniciProfili> KullaniciProfili { get; set; }
        public virtual DbSet<KullaniciSeviyeleri> KullaniciSeviyeleri { get; set; }
        public virtual DbSet<Kurslar> Kurslar { get; set; }
        public virtual DbSet<ProjeOdevTakip> ProjeOdevTakip { get; set; }
        public virtual DbSet<Referanslar> Referanslar { get; set; }
        public virtual DbSet<Resimler> Resimler { get; set; }
        public virtual DbSet<Sektorler> Sektorler { get; set; }
        public virtual DbSet<Sertifikalar> Sertifikalar { get; set; }
        public virtual DbSet<SoruCevap> SoruCevap { get; set; }
        public virtual DbSet<Yoneticiler> Yoneticiler { get; set; }
        public virtual DbSet<Yorumlar> Yorumlar { get; set; }
        public virtual DbSet<Sayac> Sayac { get; set; }
    }
}
