//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeVista.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DilKonulari
    {
        public int DilİD { get; set; }
        public int KonuİD { get; set; }
        public string DilAdi { get; set; }
        public string KullanimAlani { get; set; }
        public int SektorİD { get; set; }
        public string Amac { get; set; }
        public string PopulerlikDerecesi { get; set; }
    
        public virtual Diller Diller { get; set; }
        public virtual Konular Konular { get; set; }
        public virtual Sektorler Sektorler { get; set; }
    }
}
