//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeVista.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Diller
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Diller()
        {
            this.CalismaGruplari = new HashSet<CalismaGruplari>();
            this.EgitimKaynaklari = new HashSet<EgitimKaynaklari>();
            this.Kullaniciİstatistikleri = new HashSet<Kullaniciİstatistikleri>();
            this.Kurslar = new HashSet<Kurslar>();
            this.Referanslar = new HashSet<Referanslar>();
            this.Sektorler1 = new HashSet<Sektorler>();
            this.SoruCevap = new HashSet<SoruCevap>();
        }
    
        public int DilİD { get; set; }
        public string DilAdi { get; set; }
        public string DilTipi { get; set; }
        public int SektorİD { get; set; }
        public Nullable<int> ResimID { get; set; }
        public string resim { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CalismaGruplari> CalismaGruplari { get; set; }
        public virtual DilKonulari DilKonulari { get; set; }
        public virtual Resimler Resimler { get; set; }
        public virtual Resimler Resimler1 { get; set; }
        public virtual Sektorler Sektorler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EgitimKaynaklari> EgitimKaynaklari { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Kullaniciİstatistikleri> Kullaniciİstatistikleri { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Kurslar> Kurslar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Referanslar> Referanslar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sektorler> Sektorler1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SoruCevap> SoruCevap { get; set; }
    }
}
