//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeVista.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EgitimKaynaklari
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EgitimKaynaklari()
        {
            this.KullaniciFavorileri = new HashSet<KullaniciFavorileri>();
        }
    
        public int KaynakİD { get; set; }
        public string KaynakAdi { get; set; }
        public int KategoriİD { get; set; }
        public int DilİD { get; set; }
        public string Seviye { get; set; }
    
        public virtual Diller Diller { get; set; }
        public virtual Kategoriler Kategoriler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KullaniciFavorileri> KullaniciFavorileri { get; set; }
    }
}
