//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeVista.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class İndirimKuponlari
    {
        public int KuponİD { get; set; }
        public string KuponKodu { get; set; }
        public int İndirimYuzdesi { get; set; }
        public System.DateTime SonKullanmaTarihi { get; set; }
        public string Aciklama { get; set; }
        public Nullable<int> ResimID { get; set; }
    
        public virtual Resimler Resimler { get; set; }
    }
}
