//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeVista.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kategoriler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Kategoriler()
        {
            this.EgitimKaynaklari = new HashSet<EgitimKaynaklari>();
            this.Kategoriler1 = new HashSet<Kategoriler>();
        }
    
        public int KategoriİD { get; set; }
        public string KategoriAdi { get; set; }
        public Nullable<int> AnaKategoriİD { get; set; }
        public Nullable<int> ResimID { get; set; }
        public string resim { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EgitimKaynaklari> EgitimKaynaklari { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Kategoriler> Kategoriler1 { get; set; }
        public virtual Kategoriler Kategoriler2 { get; set; }
    }
}
