//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeVista.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kaynaklar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Kaynaklar()
        {
            this.KullaniciEtkilesimleri = new HashSet<KullaniciEtkilesimleri>();
            this.KullaniciEtkilesimleri1 = new HashSet<KullaniciEtkilesimleri>();
            this.Sayac = new HashSet<Sayac>();
        }
    
        public int KaynakİD { get; set; }
        public string KaynakAdi { get; set; }
        public string KaynakTipi { get; set; }
        public int KursİD { get; set; }
        public int SeviyeİD { get; set; }
        public Nullable<int> ResimID { get; set; }
        // Ziyaret sayısını saklamak için int türünde bir özellik
        public Nullable<int> ZiyaretSayisi { get; set; }
    
        public virtual KullaniciSeviyeleri KullaniciSeviyeleri { get; set; }
        public virtual Kurslar Kurslar { get; set; }
        public virtual Resimler Resimler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KullaniciEtkilesimleri> KullaniciEtkilesimleri { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KullaniciEtkilesimleri> KullaniciEtkilesimleri1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sayac> Sayac { get; set; }
    }
}
