//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeVista.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Konular
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Konular()
        {
            this.CalismaGruplari = new HashSet<CalismaGruplari>();
            this.DilKonulari = new HashSet<DilKonulari>();
            this.Kullaniciİstatistikleri = new HashSet<Kullaniciİstatistikleri>();
            this.Kurslar = new HashSet<Kurslar>();
        }
    
        public int KonuİD { get; set; }
        public string KonuAdi { get; set; }
        public string KonuAciklama { get; set; }
        public string KonuTipi { get; set; }
        public Nullable<int> ResimID { get; set; }
        public Nullable<int> SektorID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CalismaGruplari> CalismaGruplari { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DilKonulari> DilKonulari { get; set; }
        public virtual Resimler Resimler { get; set; }
        public virtual Sektorler Sektorler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Kullaniciİstatistikleri> Kullaniciİstatistikleri { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Kurslar> Kurslar { get; set; }
    }
}
