//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeVista.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kullanicilar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Kullanicilar()
        {
            this.Basarilar = new HashSet<Basarilar>();
            this.Bloglar = new HashSet<Bloglar>();
            this.KullaniciEtkilesimleri = new HashSet<KullaniciEtkilesimleri>();
            this.KullaniciFavorileri = new HashSet<KullaniciFavorileri>();
            this.KullaniciGeriBildirimleri = new HashSet<KullaniciGeriBildirimleri>();
            this.Kullaniciİstatistikleri = new HashSet<Kullaniciİstatistikleri>();
            this.KullaniciProfili = new HashSet<KullaniciProfili>();
            this.ProjeOdevTakip = new HashSet<ProjeOdevTakip>();
            this.Sertifikalar = new HashSet<Sertifikalar>();
            this.Yorumlar = new HashSet<Yorumlar>();
        }
    
        public int KullaniciİD { get; set; }
        public string KullaniciAdi { get; set; }
        public string HashlenmisSifre { get; set; }
        public int SeviyeİD { get; set; }
        public string Ad { get; set; }
        public string Soyad { get; set; }
        public string Email { get; set; }
        public string KullaniciRolu { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Basarilar> Basarilar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bloglar> Bloglar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KullaniciEtkilesimleri> KullaniciEtkilesimleri { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KullaniciFavorileri> KullaniciFavorileri { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KullaniciGeriBildirimleri> KullaniciGeriBildirimleri { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Kullaniciİstatistikleri> Kullaniciİstatistikleri { get; set; }
        public virtual KullaniciSeviyeleri KullaniciSeviyeleri { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KullaniciProfili> KullaniciProfili { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjeOdevTakip> ProjeOdevTakip { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sertifikalar> Sertifikalar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Yorumlar> Yorumlar { get; set; }
    }
}
