//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeVista.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kullaniciİstatistikleri
    {
        public int İstatistikİD { get; set; }
        public int KullaniciİD { get; set; }
        public int DilİD { get; set; }
        public int KonuİD { get; set; }
        public int SeviyeİD { get; set; }
        public int İlerlemeYuzdesi { get; set; }
    
        public virtual Diller Diller { get; set; }
        public virtual Konular Konular { get; set; }
        public virtual Kullanicilar Kullanicilar { get; set; }
        public virtual KullaniciSeviyeleri KullaniciSeviyeleri { get; set; }
    }
}
