//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeVista.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KullaniciFavorileri
    {
        public int FavoriİD { get; set; }
        public int KullaniciİD { get; set; }
        public int KaynakİD { get; set; }
    
        public virtual EgitimKaynaklari EgitimKaynaklari { get; set; }
        public virtual Kullanicilar Kullanicilar { get; set; }
    }
}
