//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeVista.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kurslar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Kurslar()
        {
            this.Kaynaklar = new HashSet<Kaynaklar>();
            this.ProjeOdevTakip = new HashSet<ProjeOdevTakip>();
        }
    
        public int KursİD { get; set; }
        public string KursAdi { get; set; }
        public int DilİD { get; set; }
        public int KonuİD { get; set; }
        public string KursSeviyesi { get; set; }
        public string KursAciklama { get; set; }
        public Nullable<int> ResimID { get; set; }
        public byte[] resim { get; set; }
    
        public virtual Diller Diller { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Kaynaklar> Kaynaklar { get; set; }
        public virtual Konular Konular { get; set; }
        public virtual Resimler Resimler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjeOdevTakip> ProjeOdevTakip { get; set; }
    }
}
