//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeVista.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjeOdevTakip
    {
        public int ProjeOdevİD { get; set; }
        public int KullaniciİD { get; set; }
        public int KursİD { get; set; }
        public System.DateTime SonTarih { get; set; }
        public int İlerlemeYuzdesi { get; set; }
    
        public virtual Kullanicilar Kullanicilar { get; set; }
        public virtual Kurslar Kurslar { get; set; }
    }
}
