//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeVista.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Referanslar
    {
        public int ReferansİD { get; set; }
        public string ReferansAdi { get; set; }
        public string ReferansTipi { get; set; }
        public int DilİD { get; set; }
        public Nullable<int> ResimID { get; set; }
    
        public virtual Diller Diller { get; set; }
        public virtual Resimler Resimler { get; set; }
    }
}
