//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeVista.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sayac
    {
        public Nullable<int> KaynakID { get; set; }
        public Nullable<int> BakilanSayi { get; set; }
        public int SayacİD { get; set; }
    
        public virtual Kaynaklar Kaynaklar { get; set; }
    }
}
