//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeVista.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SoruCevap
    {
        public int SoruCevapİD { get; set; }
        public string Soru { get; set; }
        public string Cevap { get; set; }
        public int DilİD { get; set; }
    
        public virtual Diller Diller { get; set; }
    }
}
