//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeVista.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Yoneticiler
    {
        public int YoneticiİD { get; set; }
        public string YoneticiAdi { get; set; }
        public string YoneticiEmail { get; set; }
        public string YoneticiSifreHash { get; set; }
        public Nullable<int> ResimID { get; set; }
    
        public virtual Resimler Resimler { get; set; }
    }
}
